enum Strings {
  ERROR_404_BUTTON_TITLE = 'Return',
  HEADER_TITLE_HOME = 'Home',
  HEADER_TITLE_CHARACTERS = 'Characters',
  HOME_BUTTON_TITLE = 'See more...',
  HOME_TITLE_TEXT_1 = 'Find ',
  HOME_TITLE_TEXT_2 = 'all your favorite ',
  HOME_TITLE_TEXT_3 = 'character',
  HOME_SUBTITLE_TEXT = 'You can find out all the information about your favorite characters',
  CHARACTERS_TITLE_TEXT_1 = ' Peoples ',
  CHARACTERS_TITLE_TEXT_2 = 'for you to choose your favorite',
  CHARACTERS_END_TEXT = 'No more characters in the moment',
  CHARACTERS_EMPTY_TEXT = 'Oops... Nothing seems to be found -_-',
  INFO_MALE = 'male',
  INFO_FEMALE = 'female',
  INFO_MASS = 'mass',
  INFO_HEIGHT = 'height',
  INFO_PROPS_HAIR_COLOR = 'hair color: ',
  INFO_PROPS_SKIN_COLOR = 'skin color: ',
}
export default Strings;
